# **XGBoost** классификация

это реализация градиентного бустинга над деревьями решений с регуляризацией, которая последовательно добавляет новые деревья, уменьшая ошибку предыдущих и тем самым строя сильную модель из множества слабых.

In [1]:
import xgboost as xgb # type: ignore
import pandas as pd
from data_preprocessing.DataForModel import build_target, split_data, preprocess_dataset

ModuleNotFoundError: No module named 'data_preprocessing'

In [80]:
name = input("Введите имя файла большими буквами: ")
DF: pd.DataFrame = pd.read_csv(f"/Users/side/Desktop/Trading Chaos AI/df/clean_df/{name}.csv")

In [83]:
DF = preprocess_dataset(DF)

NameError: name 'preprocess_dataset' is not defined

In [79]:
df = build_target(df, h=20, target_type="classification")

y = df["GoodTrade"]

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36352 entries, 0 to 36351
Data columns (total 35 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   DateTime              36352 non-null  object
 1   Open                  36352 non-null  float64
 2   High                  36352 non-null  float64
 3   Low                   36352 non-null  float64
 4   Close                 36352 non-null  float64
 5   Alligator_Jaw         36352 non-null  float64
 6   Alligator_Teeth       36352 non-null  float64
 7   Alligator_Lips        36352 non-null  float64
 8   Fractal_Up            36352 non-null  int64
 9   Fractal_Down          36352 non-null  int64
 10  AO                    36352 non-null  float64
 11  Color AO              36352 non-null  int64
 12  Alligator_Bullish     36352 non-null  int64
 13  Alligator_Bearish     36352 non-null  int64
 14  AlligatorStart_Long   36352 non-null  int64
 15  AlligatorStart_Short  36352 non-null  int64
 16  AO_sign               36352 non-null  int64
 17  AO_zero_up            36352 non-null  int64
 18  AO_zero_down          36352 non-null  int64
 19  AO_three_green        36352 non-null  int64
 20  AO_three_red          36352 non-null  int64
 21  AO_saucer_up          36352 non-null  int64
 22  AO_saucer_down        36352 non-null  int64
 23  EntrySignal           36352 non-null  int64
 24  EntryReason           1830 non-null   object
 25  Fractal_Up_conf       36352 non-null  int64
 26  Fractal_Down_conf     36352 non-null  int64
 27  AddOn_Anchor_Level    36352 non-null  float64
 28  AddOn_Anchor_IsUp     36352 non-null  float64
 29  AddOn_Size_Pct        36352 non-null  float64
 30  AddOn_Ready           36352 non-null  int64
 31  AddOn_Triggered       36352 non-null  int64
 32  Close_fwd             36352 non-null  float64
 33  ret_H                 36352 non-null  float64
 34  GoodTrade             36352 non-null  int64
dtypes: float64(13), int64(20), object(2)
memory usage: 10.0+ MB

In [71]:
df

,Open,High,Low,Close,Alligator_Jaw,Alligator_Teeth,Alligator_Lips,Fractal_Up,Fractal_Down,AO,...,Fractal_Up_conf,Fractal_Down_conf,AddOn_Anchor_Level,AddOn_Anchor_IsUp,AddOn_Size_Pct,AddOn_Ready,AddOn_Triggered,Close_fwd,ret_H,GoodTrade
0,-0.882804,-0.885006,-0.881681,-0.882997,-0.877243,-0.880793,-0.882803,0,0,-0.076686,...,0,1,-0.888653,0.0,0.0,1,1,-0.875703,0.0,0
1,-0.883260,-0.884854,-0.881986,-0.883756,-0.877589,-0.880604,-0.882814,0,0,-0.084363,...,1,0,-0.888653,0.0,0.0,0,0,-0.874183,0.0,0
2,-0.883108,-0.884703,-0.884879,-0.886339,-0.877763,-0.880543,-0.882277,1,0,-0.095493,...,0,0,-0.888653,0.0,0.0,0,0,-0.875399,0.0,0
3,-0.885994,-0.887280,-0.884574,-0.886795,-0.877749,-0.880593,-0.882227,0,0,-0.112924,...,0,0,-0.888653,0.0,0.0,0,0,-0.875399,0.0,0
4,-0.887058,-0.888948,-0.886249,-0.887707,-0.877724,-0.880296,-0.882202,0,1,-0.176271,...,1,0,-0.888653,0.0,0.0,0,0,-0.875551,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36347,3.925034,3.945346,3.938937,3.950615,3.784252,3.787165,3.812680,1,0,3.373438,...,0,0,3.730041,0.0,0.0,0,0,3.616320,0.0,0
36348,3.944934,3.938827,3.951272,3.947880,3.786227,3.791637,3.829056,0,0,4.711882,...,0,0,3.730041,0.0,0.0,0,0,3.664033,0.0,0
36349,3.946909,3.942465,3.945180,3.948944,3.787916,3.802417,3.842278,0,0,5.392100,...,1,0,3.730041,0.0,0.0,0,0,3.621334,0.0,0
36350,3.947972,3.966571,3.958885,3.970217,3.789235,3.813833,3.861967,0,0,6.052040,...,0,0,3.730041,0.0,0.0,0,0,3.520590,0.0,0
36351,3.968935,3.987644,3.982640,3.996201,3.791760,3.823897,3.878295,1,0,6.917860,...,0,0,3.730041,0.0,0.0,0,0,3.533961,0.0,0

In [74]:
X_train, X_test, y_train, y_test = split_data(df, target="GoodTrade", val_size=0.1, test_size=0.2, split_type="train_test")

print(f"X_train: {X_train.shape}, X_test: {X_test.shape}")

X_train: (29081, 33), X_test: (7271, 33)

In [65]:
import pandas as pd

In [68]:
df.describe()

,Open,High,Low,Close,Alligator_Jaw,Alligator_Teeth,Alligator_Lips,Fractal_Up,Fractal_Down,AO,...,Fractal_Up_conf,Fractal_Down_conf,AddOn_Anchor_Level,AddOn_Anchor_IsUp,AddOn_Size_Pct,AddOn_Ready,AddOn_Triggered,Close_fwd,ret_H,GoodTrade
count,36352.000000,36352.000000,36352.000000,36352.000000,36352.000000,36352.000000,36352.000000,36352.000000,36352.000000,36352.000000,...,36352.000000,36352.000000,36352.000000,36352.000000,36352.0,36352.000000,36352.000000,36352.000000,36352.000000,36352.000000
mean,0.068465,0.068182,0.068923,0.068482,0.069401,0.069129,0.068407,0.132812,0.133610,0.046374,...,0.132812,0.133638,0.053999,0.523933,0.0,0.023190,0.023190,0.071007,-0.000940,0.025886
std,0.910752,0.910449,0.911479,0.911152,0.905165,0.907348,0.908912,0.339377,0.340238,1.119807,...,0.339377,0.340267,0.895428,0.499434,0.0,0.150508,0.150508,0.914865,0.249652,0.158797
min,-1.063725,-1.065418,-1.064565,-1.064428,-1.047792,-1.053357,-1.058578,0.000000,0.000000,-8.645734,...,0.000000,0.000000,-1.068323,0.000000,0.0,0.000000,0.000000,-1.064428,-20.000000,0.000000
25%,-0.685060,-0.685946,-0.684635,-0.685306,-0.681424,-0.682671,-0.684337,0.000000,0.000000,-0.481664,...,0.000000,0.000000,-0.692471,0.000000,0.0,0.000000,0.000000,-0.685002,0.000000,0.000000
50%,-0.000076,-0.000303,-0.000305,-0.000304,-0.000224,-0.000396,-0.000251,0.000000,0.000000,0.000543,...,0.000000,0.000000,0.000000,1.000000,0.0,0.000000,0.000000,0.000456,0.000000,0.000000
75%,0.314408,0.313448,0.314908,0.314390,0.317936,0.317034,0.315338,0.000000,0.000000,0.517962,...,0.000000,0.000000,0.306014,1.000000,0.0,0.000000,0.000000,0.314846,0.000000,0.000000
max,3.979872,3.987644,3.982640,3.996201,3.841002,3.877144,3.904416,1.000000,1.000000,9.489803,...,1.000000,1.000000,3.730041,1.000000,0.0,1.000000,1.000000,3.996201,15.800000,1.000000

In [69]:
# Обучаем XGBoost для классификации
model = xgb.XGBClassifier(use_label_encoder=False, eval_metric="logloss")

# Тренировка модели
model.fit(X_train, y_train)

# Прогнозируем на тестовой выборке
y_pred = model.predict(X_test)

# Оценка модели
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

ValueError: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, the experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:DateTime: object, EntryReason: object

настройка баланса классов

In [ ]:
# баланс классов
pos = (y_train == 1).sum()
neg = (y_train == 0).sum()
scale_pos_weight = neg / pos if pos > 0 else 1.0
print(f"pos={pos}, neg={neg}, scale_pos_weight={scale_pos_weight:.2f}")

pos=701, neg=729, scale_pos_weight=1.04

Модель

In [ ]:
model = xgb.XGBClassifier(
    objective='binary:logistic',
    n_estimators=1000,
    max_depth=3,
    learning_rate=0.05,
    subsample=0.7,
    colsample_bytree=0.7,
    reg_lambda=2.0,
    scale_pos_weight=scale_pos_weight,
    tree_method="hist",
    eval_metric="auc",
)

model.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],   # будем смотреть AUC на тесте
    verbose=50                     # печатать лог каждые 50 итераций
)

[0]	validation_0-auc:0.51445
[50]	validation_0-auc:0.54657
[100]	validation_0-auc:0.55216
[150]	validation_0-auc:0.55943
[200]	validation_0-auc:0.54849
[250]	validation_0-auc:0.53724
[300]	validation_0-auc:0.53451
[350]	validation_0-auc:0.53663
[400]	validation_0-auc:0.53510
[450]	validation_0-auc:0.53723
[500]	validation_0-auc:0.53395
[550]	validation_0-auc:0.53179
[600]	validation_0-auc:0.53157
[650]	validation_0-auc:0.53182
[700]	validation_0-auc:0.52951
[750]	validation_0-auc:0.52954
[800]	validation_0-auc:0.52389
[850]	validation_0-auc:0.52232
[900]	validation_0-auc:0.51883
[950]	validation_0-auc:0.52236
[999]	validation_0-auc:0.52111

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.7, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=1000,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
from sklearn.metrics import roc_auc_score, classification_report, confusion_matrix

# вероятности того, что сделка хорошая
proba_test = model.predict_proba(X_test)[:, 1]

# можно взять порог 0.5 (потом поиграемся)
y_pred = (proba_test >= 0.5).astype(int)

print("AUC на тесте:", roc_auc_score(y_test, proba_test))
print()
print("Отчёт по классификации:")
print(classification_report(y_test, y_pred))

print("Матрица ошибок:")
print(confusion_matrix(y_test, y_pred))

AUC на тесте: 0.5211060771754413

Отчёт по классификации:
              precision    recall  f1-score   support

           0       0.53      0.60      0.56       185
           1       0.51      0.44      0.47       173

    accuracy                           0.52       358
   macro avg       0.52      0.52      0.52       358
weighted avg       0.52      0.52      0.52       358

Матрица ошибок:
[[111  74]
 [ 97  76]]

In [ ]:
import pandas as pd
import numpy as np

importances = model.feature_importances_
fi = pd.DataFrame({'feature': feature_cols, 'importance': importances})
fi = fi.sort_values('importance', ascending=False)
fi.head(20)