# Авторегрессия (AR) 

— это метод прогнозирования, который основывается на идее, что текущее значение временного ряда можно выразить как линейную комбинацию его предыдущих значений. Эта модель активно используется для анализа и прогнозирования временных рядов, например, в экономике, финансах и других областях, где данные демонстрируют определенную последовательность.

## Основные концепции авторегрессии:
	1.	Стационарность: Важнейшее требование для модели AR. Это означает, что среднее и дисперсия временного ряда остаются неизменными на протяжении времени. Если данные не являются стационарными, их необходимо привести к стационарному виду, например, путем дифференцирования.
	2.	Порядок модели AR(p): В модели AR(p), где p — это порядок модели, текущее значение зависит от p предыдущих значений временного ряда. Например, AR(1) использует только одно предыдущее значение, AR(2) — два, и так далее.
	3.	Формула AR(p):
$$
X_t = \phi_1 X_{t-1} + \phi_2 X_{t-2} + \dots + \phi_p X_{t-p} + \epsilon_t
$$
где:
	•	$$ X_t $$ — текущее значение,
	•	$$ \phi_1, \phi_2, \dots, \phi_p $$ — коэффициенты модели,
	•	$$ \epsilon_t $$ — ошибка модели (шум).
	4.	AR(1): Простейшая форма авторегрессии, где текущее значение зависит только от одного предыдущего значения:
$$
X_t = \phi_1 X_{t-1} + \epsilon_t
$$ 
Здесь $ \phi_1 $ — коэффициент, определяющий, насколько сильно текущее значение зависит от прошлого.
	5.	Оценка параметров: Для определения коэффициентов модели \phi используются различные методы, такие как метод наименьших квадратов (МНК) или метод максимального правдоподобия (ММП).
	6.	Тестирование на стационарность: Перед использованием модели AR необходимо проверить стационарность ряда с помощью ADF-теста (Augmented Dickey-Fuller). Если p-value теста меньше 0.05, то ряд стационарен и можно применять AR-модель. Если ряд нестационарен, его нужно дифференцировать.
	7.	Диагностика модели: После построения модели важно провести диагностику остатков, чтобы убедиться, что ошибка случайна и не содержит значимых паттернов.

1 шаг: Выбираем данные на которых будем обучать. Так как для AR лучше чтобы данные были стационарными

In [2]:
import pandas as pd

In [6]:
name = name = input("Введите название инструмента(пример: AFKS, Gold, YDEX):")
df = pd.read_csv(f'../df/clean_df/{name}.csv')
df

,DateTime,Open,High,Low,Close,Alligator_Jaw,Alligator_Teeth,Alligator_Lips,Fractal_Up,Fractal_Down,...,AO_saucer_down,EntrySignal,EntryReason,Fractal_Up_conf,Fractal_Down_conf,AddOn_Anchor_Level,AddOn_Anchor_IsUp,AddOn_Size_Pct,AddOn_Ready,AddOn_Triggered
0,2015-10-26 10:00:00,1167.4,1167.7,1164.1,1164.7,1172.08245,1169.95638,1168.23074,0,0,...,0,0,NaN,0,0,NaN,NaN,NaN,0,0
1,2015-10-26 11:00:00,1164.5,1168.4,1164.2,1167.7,1171.51841,1169.40558,1168.13460,0,0,...,0,0,NaN,0,0,NaN,NaN,NaN,0,0
2,2015-10-26 12:00:00,1167.7,1168.8,1166.3,1168.0,1171.01700,1169.11738,1167.89768,0,0,...,0,-1,three_color,0,0,NaN,NaN,NaN,0,0
3,2015-10-26 13:00:00,1168.0,1170.5,1167.6,1169.5,1170.55800,1168.94646,1167.49814,1,0,...,0,0,NaN,0,0,NaN,NaN,NaN,0,0
4,2015-10-26 14:00:00,1169.3,1169.8,1168.5,1169.5,1170.17277,1168.69690,1167.25851,0,0,...,0,0,NaN,0,0,NaN,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36375,2025-10-21 23:00:00,4112.0,4132.2,4109.3,4130.0,4288.22638,4245.82389,4181.94455,0,0,...,0,0,NaN,0,0,4217.0,0.0,0.3,0,0
36376,2025-10-22 09:00:00,4134.9,4167.3,4127.2,4161.4,4281.47050,4230.51465,4169.21564,1,0,...,0,0,NaN,0,0,4217.0,0.0,0.3,0,0
36377,2025-10-22 10:00:00,4161.5,4162.4,4131.5,4133.3,4270.39585,4215.16907,4157.66252,0,0,...,0,0,NaN,0,0,4217.0,0.0,0.3,0,0
36378,2025-10-22 11:00:00,4133.3,4135.0,4059.5,4067.0,4260.14617,4203.06044,4150.28001,0,0,...,1,-1,saucer,1,0,4217.0,0.0,0.3,0,0
36379,2025-10-22 12:00:00,4067.4,4101.2,4067.0,4075.8,4249.62339,4191.60913,4149.67401,0,0,...,0,0,NaN,0,0,4217.0,0.0,0.3,0,0

In [8]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Open,36380.0,1796.305874,6.020440e+02,1049.80000,1299.000000,1750.05000,1957.300000,4380.40000
High,36380.0,1798.912763,6.030419e+02,1050.00000,1300.300000,1752.75000,1959.900000,4383.00000
Low,36380.0,1793.632402,6.010093e+02,1048.10000,1297.600000,1747.20000,1954.300000,4362.60000
Close,36380.0,1796.345701,6.020937e+02,1049.60000,1299.100000,1750.10000,1957.200000,4380.00000
Alligator_Jaw,36380.0,1794.608755,5.994451e+02,1056.82964,1298.362515,1747.62345,1957.647567,4302.07032
Alligator_Teeth,36380.0,1795.285486,6.005259e+02,1054.44959,1298.683397,1748.50810,1957.585015,4319.90682
Alligator_Lips,36380.0,1795.702183,6.011728e+02,1052.33628,1298.776370,1749.43602,1957.301200,4338.17626
Fractal_Up,36380.0,0.132793,3.393553e-01,0.00000,0.000000,0.00000,0.000000,1.00000
Fractal_Down,36380.0,0.133617,3.402454e-01,0.00000,0.000000,0.00000,0.000000,1.00000
AO,36380.0,1.212287,1.380942e+01,-133.63000,-5.200513,0.67250,6.982425,116.28618
Color AO,36380.0,0.001869,9.999295e-01,-1.00000,-1.000000,1.00000,1.000000,1.00000
Alligator_Bullish,36380.0,0.438510,4.962114e-01,0.00000,0.000000,0.00000,1.000000,1.00000
Alligator_Bearish,36380.0,0.373117,4.836395e-01,0.00000,0.000000,0.00000,1.000000,1.00000
AlligatorStart_Long,36380.0,0.025646,1.580789e-01,0.00000,0.000000,0.00000,0.000000,1.00000
AlligatorStart_Short,36380.0,0.026306,1.600449e-01,0.00000,0.000000,0.00000,0.000000,1.00000
AO_sign,36380.0,0.001704,1.000012e+00,-1.00000,-1.000000,1.00000,1.000000,1.00000
AO_zero_up,36380.0,0.020753,1.425589e-01,0.00000,0.000000,0.00000,0.000000,1.00000
AO_zero_down,36380.0,0.020753,1.425589e-01,0.00000,0.000000,0.00000,0.000000,1.00000
AO_three_green,36380.0,0.344887,4.753380e-01,0.00000,0.000000,0.00000,1.000000,1.00000
AO_three_red,36380.0,0.343238,4.747967e-01,0.00000,0.000000,0.00000,1.000000,1.00000
AO_saucer_up,36380.0,0.037905,1.909702e-01,0.00000,0.000000,0.00000,0.000000,1.00000
AO_saucer_down,36380.0,0.031089,1.735593e-01,0.00000,0.000000,0.00000,0.000000,1.00000
EntrySignal,36380.0,-0.000357,2.244684e-01,-1.00000,0.000000,0.00000,0.000000,1.00000
Fractal_Up_conf,36380.0,0.132793,3.393553e-01,0.00000,0.000000,0.00000,0.000000,1.00000
Fractal_Down_conf,36380.0,0.133617,3.402454e-01,0.00000,0.000000,0.00000,0.000000,1.00000
AddOn_Anchor_Level,36372.0,1791.779259,5.936414e+02,1049.60000,1297.700000,1754.80000,1957.800000,4217.00000
AddOn_Anchor_IsUp,36372.0,0.523645,4.994475e-01,0.00000,0.000000,1.00000,1.000000,1.00000
AddOn_Size_Pct,36372.0,0.300000,5.551191e-17,0.30000,0.300000,0.30000,0.300000,0.30000
AddOn_Ready,36380.0,0.023172,1.504518e-01,0.00000,0.000000,0.00000,0.000000,1.00000
AddOn_Triggered,36380.0,0.023172,1.504518e-01,0.00000,0.000000,0.00000,0.000000,1.00000

In [3]:
from statsmodels.tsa.stattools import adfuller
adf_result = adfuller(df['DateTime'])
adf_result

ModuleNotFoundError: No module named 'statsmodels'